//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchPayment
    {
        public AchPayment()
        {
            this.AchTransactions = new HashSet<AchTransaction>();
        }
    
        public int Id { get; set; }
        public string MerchantId { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<bool> Saved { get; set; }
    
        public virtual ICollection<AchTransaction> AchTransactions { get; set; }
    }
}
