//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchTransaction
    {
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> TimeSpan { get; set; }
    
        public virtual AchPayment AchPayment { get; set; }
    }
}
