//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlackstonePos_Entities : DbContext
    {
        public BlackstonePos_Entities()
            : base("name=BlackstonePos_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AchTransaction> AchTransactions { get; set; }
        public DbSet<Cashier> Cashiers { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<AchPayment> AchPayments { get; set; }
        public DbSet<Promotion> Promotions { get; set; }
        public DbSet<Applicant> Applicants { get; set; }
    }
}
