//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BlackstonePos_NewEntities : DbContext
    {
        public BlackstonePos_NewEntities()
            : base("name=BlackstonePos_NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AchPayment> AchPayments { get; set; }
        public DbSet<AchTransaction> AchTransactions { get; set; }
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<Cashier> Cashiers { get; set; }
        public DbSet<Guest> Guests { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<PaxPosOrderRequest> PaxPosOrderRequests { get; set; }
        public DbSet<PaxPosOrderResult> PaxPosOrderResults { get; set; }
        public DbSet<PaxPosPendingOrder> PaxPosPendingOrders { get; set; }
        public DbSet<Product_ActionMapping> Product_ActionMapping { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<cashiers_backup> cashiers_backup { get; set; }
        public DbSet<pos_mainproducts> pos_mainproducts { get; set; }
        public DbSet<view_cashiers> view_cashiers { get; set; }
        public DbSet<AppLogoUrl> AppLogoUrls { get; set; }
        public DbSet<FullCargaSmsTemplate> FullCargaSmsTemplates { get; set; }
    
        public virtual ObjectResult<getPromotios_Result> getPromotios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPromotios_Result>("getPromotios");
        }
    
        public virtual int sp_get_merchant_commission(Nullable<int> merchant_fk, string product_sbt, Nullable<decimal> pro_amount, Nullable<decimal> pro_fee)
        {
            var merchant_fkParameter = merchant_fk.HasValue ?
                new ObjectParameter("merchant_fk", merchant_fk) :
                new ObjectParameter("merchant_fk", typeof(int));
    
            var product_sbtParameter = product_sbt != null ?
                new ObjectParameter("product_sbt", product_sbt) :
                new ObjectParameter("product_sbt", typeof(string));
    
            var pro_amountParameter = pro_amount.HasValue ?
                new ObjectParameter("pro_amount", pro_amount) :
                new ObjectParameter("pro_amount", typeof(decimal));
    
            var pro_feeParameter = pro_fee.HasValue ?
                new ObjectParameter("pro_fee", pro_fee) :
                new ObjectParameter("pro_fee", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_merchant_commission", merchant_fkParameter, product_sbtParameter, pro_amountParameter, pro_feeParameter);
        }
    }
}
