//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashiers_backup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int MerchantId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsMerchant { get; set; }
    }
}
