//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public string ProductMainCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OperatorName { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string PinID { get; set; }
        public string PinNumber { get; set; }
        public string ControlNumber { get; set; }
        public string AuthorizationCode { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string BillerId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public string TerminalId { get; set; }
        public string Source { get; set; }
        public string ConfirmationPhoneNumber { get; set; }
        public Nullable<bool> Refunded { get; set; }
        public string ConfirmationMessage { get; set; }
        public string ProductCategory { get; set; }
    }
}
