//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaxPosPendingOrder
    {
        public int Id { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderExpirationDate { get; set; }
    }
}
