//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaxPosOrderRequest
    {
        public int OrderId { get; set; }
        public string CashierId { get; set; }
        public string ProductId { get; set; }
        public Nullable<int> Type { get; set; }
        public string ProductName { get; set; }
        public string VendorId { get; set; }
        public string AccountNumber { get; set; }
        public string AltAccountNumber { get; set; }
        public string AddInfo1 { get; set; }
        public string AddInfo2 { get; set; }
        public string CustomerName { get; set; }
        public string SenderName { get; set; }
        public string LicensePlate { get; set; }
        public string TotalAmount { get; set; }
        public string Country { get; set; }
        public string PhoneNumber { get; set; }
        public string VendorPaymentType { get; set; }
        public string VendorRemitTimming { get; set; }
        public Nullable<double> Fee { get; set; }
        public string PurchaseId { get; set; }
        public string PaymentKeyWord { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
        public Nullable<bool> HasAccessNumbers { get; set; }
        public Nullable<bool> HasSunPassDocuments { get; set; }
    }
}
