//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class pin_dataEntities : DbContext
    {
        public pin_dataEntities()
            : base("name=pin_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PosmerchantHeader> PosmerchantHeaders { get; set; }
        public DbSet<posinvoicedetail> posinvoicedetails { get; set; }
        public DbSet<posinvoiceheader> posinvoiceheaders { get; set; }
        public DbSet<Posterminal> Posterminals { get; set; }
    
        public virtual int SerialVerificationDisactivation(Nullable<int> merchantId, Nullable<int> terminalId, string serialNumber)
        {
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("merchantId", merchantId) :
                new ObjectParameter("merchantId", typeof(int));
    
            var terminalIdParameter = terminalId.HasValue ?
                new ObjectParameter("terminalId", terminalId) :
                new ObjectParameter("terminalId", typeof(int));
    
            var serialNumberParameter = serialNumber != null ?
                new ObjectParameter("serialNumber", serialNumber) :
                new ObjectParameter("serialNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SerialVerificationDisactivation", merchantIdParameter, terminalIdParameter, serialNumberParameter);
        }
    }
}
