//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackstonePos.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posterminal
    {
        public int terminal_pk { get; set; }
        public Nullable<int> merchant_fk { get; set; }
        public Nullable<int> merchant_StoreNo { get; set; }
        public string custno_fk { get; set; }
        public Nullable<decimal> terminal_id { get; set; }
        public string ter_location { get; set; }
        public string ter_datein { get; set; }
        public Nullable<System.DateTime> ter_dateout { get; set; }
        public Nullable<System.DateTime> ter_timestamp { get; set; }
        public string ter_useradder { get; set; }
        public Nullable<System.DateTime> ter_dateadded { get; set; }
        public string ter_usereditor { get; set; }
        public Nullable<System.DateTime> ter_dateeditor { get; set; }
        public short EPICNETZ_status { get; set; }
        public Nullable<System.DateTime> EPICNETZ_date { get; set; }
        public string USBSettleTime { get; set; }
        public bool Programload { get; set; }
        public bool ReInit { get; set; }
        public string ReloadTime { get; set; }
        public string LastEvent { get; set; }
        public Nullable<System.DateTime> LastEventDate { get; set; }
        public string SerialNo { get; set; }
        public int Stran { get; set; }
        public string Alert { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public Nullable<bool> serial_verified { get; set; }
        public Nullable<System.DateTime> serial_verified_date { get; set; }
        public Nullable<bool> deployed { get; set; }
        public string ANI { get; set; }
        public Nullable<bool> DEMO { get; set; }
        public Nullable<float> TAX { get; set; }
        public string ReInitType { get; set; }
        public string AdditionalTableCode { get; set; }
        public string cashierId { get; set; }
        public Nullable<short> cashierStatus { get; set; }
        public Nullable<bool> closing { get; set; }
        public Nullable<System.DateTime> closingTimeout { get; set; }
        public Nullable<System.DateTime> closedate { get; set; }
        public Nullable<bool> closeoutActive { get; set; }
        public Nullable<bool> changeSerialNo { get; set; }
    }
}
